#!/bin/sh

## Set variables.
scr=./script/PDN_script/add_vdd_via.scr
metal1=M4
metal2=M3
pos_file=./die_data/INTERPOSER_vdd_position.txt

## Generate script file.
echo -e "## Allegro VDD Via insertion script." > $scr
echo -e "## generated by JKIM." >> $scr
echo -e "\n" >> $scr
echo -e "version 17.2" >> $scr
echo -e "\n" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "trapsize 3634" >> $scr
echo -e "generaledit" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "\n" >> $scr
echo -e "## Add Via" >> $scr
echo -e "add connect" >> $scr
echo -e "setwindow form.mini" >> $scr
echo -e "FORM mini active_subclass $metal1 " >> $scr
echo -e "FORM mini alt_subclass $metal2 " >> $scr
echo -e "setwindow form.mini" >> $scr
echo -e "\n" >> $scr

for position in ` cat $pos_file `
do
	echo -e "pick grid\t$position" >> $scr
	echo -e "pick grid\t$position" >> $scr
	echo -e "pick grid dbl\t$position" >> $scr
	echo -e "prepopup\t$position" >> $scr
	echo -e "next" >> $scr
done

echo -e "\n" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "\n" >> $scr
echo -e "done" >> $scr

sed -i 's/_/\t/' $scr
