#!/bin/sh

## Set variables.
scr=./script/PDN_script/add_vss_line.scr
metal=M4
pos_file=./die_data/INTERPOSER_vss_position.txt

## Generate script file.
echo -e "## Allegro VSS line insertion script." > $scr
echo -e "## generated by JKIM." >> $scr
echo -e "\n" >> $scr
echo -e "version 17.2" >> $scr
echo -e "\n" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "trapsize 2620" >> $scr
echo -e "generaledit" >> $scr
echo -e "setwindow form.mini" >> $scr
echo -e "FORM mini subclass $metal" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "\n" >> $scr

echo -e "## Add Rect" >> $scr
echo -e "generaledit" >> $scr
echo -e "add rect" >> $scr
echo -e "setwindow form.mini" >> $scr
echo -e "FORM mini rec_place YES" >> $scr
echo -e "FORM mini rec_width 65.00" >> $scr
echo -e "FORM mini rec_height 12.00" >> $scr
echo -e "setwindow pcb" >> $scr
echo -e "\n" >> $scr

for position in ` cat $pos_file `
do
	echo -e "pick grid\t$position" >> $scr
	echo -e "fillin\t\"Vss\"" >> $scr
done

echo -e "done" >> $scr

sed -i 's/_/\t/' $scr

sed -i 's/rec\tplace/rec_place/' $scr
sed -i 's/rec\twidth/rec_width/' $scr
sed -i 's/rec\theight/rec_height/' $scr
